### ISSUE TITLE
ImportError - cannot import name 'register_matplotlib_converters' from 'pandas.plotting'

### ISSUE THREAD

**Issue by castorfou** [pandas-profiling/pandas-profiling#228]
**Describe the bug**

ImportError when running for the 1st time after a fresh pandas-profiling install with a very simple code.

**To Reproduce**

conda install -c conda-forge pandas-profiling

#%% test pandas-profiling
import pandas as pd
import pandas_profiling

wells=pd.read_csv('wells.csv', index_col=0)
wells.profile_report(style={'full_width':True})

_Data:_
https://file.io/fOIwb5 as wells.csv

_Code:_ Preferably, use this code format:
```python
"""
Test for issue ImportError cannot import name 'register_matplotlib_converters' from 'pandas.plotting':
https://github.com/pandas-profiling/pandas-profiling/issues/XXX
"""
import pandas as pd
import pandas_profiling


wells=pd.read_csv('wells.csv', index_col=0)
wells.profile_report(style={'full_width':True})
```

**Version information:**

Version information is essential in reproducing and resolving bugs. Please report:

* _Python version_: 3.7.3
* _Environment_: Spyder
* _`pip`_:

<details><summary>Click to expand <strong><em>Version information</em></strong></summary>
<p>

```
alabaster==0.7.12
altair==3.1.0
asn1crypto==0.24.0
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.7.0
backcall==0.1.0
bleach==3.1.0
branca==0.3.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
cloudpickle==1.2.1
colorama==0.4.1
confuse==1.0.0
cryptography==2.7
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
docutils==0.14
entrypoints==0.3
folium==0.9.1
htmlmin==0.1.12
idna==2.8
imagesize==1.1.0
importlib-metadata==0.18
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.3.1
jupyter-core==4.5.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
llvmlite==0.29.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
more-itertools==7.2.0
nbconvert==5.5.0
nbformat==4.4.0
notebook==6.0.0
numba==0.45.0
numpy==1.16.4
numpydoc==0.9.1
packaging==19.0
pandas==0.24.2
pandas-profiling==2.3.0
pandocfilters==1.4.2
parso==0.5.0
patsy==0.5.1
phik==0.9.8
pickleshare==0.7.5
pluggy==0.12.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
psutil==5.6.3
PuLP==1.6.8
py==1.8.0
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrsistent==0.14.11
PySocks==1.7.0
pytest==5.0.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.1
pytest-pylint==0.14.0
pytest-remotedata==0.3.1
pytest-runner==5.1
python-dateutil==2.8.0
pytz==2019.1
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.5.1
QtPy==1.8.0
requests==2.22.0
rope==0.14.0
scipy==1.3.0
seaborn==0.9.0
Send2Trash==1.5.0
six==1.12.0
snowballstemmer==1.9.0
Sphinx==2.1.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
spyder==3.3.6
spyder-kernels==0.5.1
statsmodels==0.10.0
terminado==0.8.2
testpath==0.4.2
toolz==0.10.0
tornado==6.0.3
traitlets==4.3.2
urllib3==1.24.2
vincent==0.4.4
wcwidth==0.1.7
webencodings==0.5.1
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.2
zipp==0.5.1
```

</p>
</details>

**Additional context**

**Comment by sbrugman** [comment]
The version information seems correct. This is most likely not a problem with pandas-profiling itself.

You could uninstall pandas/matplotlib and restart the environment. Does it work then?

Related: https://github.com/pandas-dev/pandas/issues/19340

**Comment by castorfou** [comment]
fixed by just restarting the environment, thanks!

**Comment by ngupta23** [comment]
@castorfou - can you provide the instructions to "restart" the env. I tried to deactivate it and then activate it again, but the issue persists.

**Comment by hendyzone** [comment]
> @castorfou - can you provide the instructions to "restart" the env. I tried to deactivate it and then activate it again, but the issue persists.

He means "restart jupyter"

**Comment by nateGeorge** [comment]
For me, I needed to either run the jupyter notebook from the same terminal where I upgraded pandas-profiling, or open a new terminal window.
